name: ModernBedWars-Stats-For-Clans
version: ${project.version}
author: Simonsator
depends: [Clans]
main: de.simonsator.partyandfriends.clans.stats.marcelybedwars.MBStatsMain
description: Provides stats for clans for Marcely Bedwars